### PR TITLE
Develop 1.8

### PR DESCRIPTION
**Pull request by Kan18**
develop 1.8

### CODE REVIEW

**Comment by Kan18** [comment]
Whoops, I created this PR accidentally. I'll leave it open because I think we need to fix the issue of all the development happening on develop-1.8. Maybe we could have a system where master-1.8 is the recommended version, new features get added to develop-1.8 , and every 10 days we make a pull request from develop-1.8 to master-1.8 with a version number. While we're at it, we might want to add some more configuration to the installer, such as whether to boot into opus shell or Overview the first time, and whether to include UI applications. For this we could create a CLI version of the welcome app, or include the welcome app in the installer. Also, some things shouldn't be installed on every computer, such as 6.tl3.lua, we could have special cases to make the installer detect if the system is a turtle, to save space.

**Comment by Kan18** [comment]
We could also have a installer that customizes for the user's needs, like early versions of the Mac operating system: 
image

**Comment by hugeblank** [comment]
I disagree with the whole every 10 days we should push to master, I don't think any element of this project should have a time limit to it.

**Comment by Kan18** [comment]
> I disagree with the whole every 10 days we should push to master, I don't think any element of this project should have a time limit to it.

The "every 10 days" was just as an example, but what I'm saying is that we should have a "bleeding edge" and "stable" branch where features are first tested in the bleeding-edge branch then moved to stable soon. The accepted standard of using develop-1.8 instead of master-1.8 is very confusing for people.

**Pull request merged**
